trigger:
  branches:
    include:
      - develop
      - main

pool:
  vmImage: 'ubuntu-latest'

  
resources:
  repositories:
    - repository: notificaciones
      name:  DS2-Devops/notificaciones
      type: git

variables:
  - ${{ if eq(variables['Build.SourceBranchName'], 'develop') }}:
      - group: s3-environments-dev
  - ${{ if eq(variables['Build.SourceBranchName'], 'main') }}:
      - group: s3-environments-pdn
  - group: GoogleChatWebhook

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'Install dependencies'

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'SonarCloudService' # Nombre del servicio de conexión de SonarCloud en Azure DevOps
    organization: 'ds2team9' # Nombre de tu organización en SonarCloud
    scannerMode: 'CLI'
    configMode: 'manual'
    cliProjectKey: 'Blessed0314_RickAndMorty2.0' # Clave del proyecto en SonarCloud
    cliProjectName: 'RickAndMorty2.0' # Nombre del proyecto en SonarCloud
    cliSources: '.'
    extraProperties: |
      sonar.javascript.lcov.reportPaths=coverage/lcov.info

- script: |
    npm run build
  displayName: 'Build the project'

- script: |
    npm test -- --coverage
  displayName: 'Run tests with coverage'

- task: SonarCloudAnalyze@1
  displayName: 'Run SonarCloud analysis'

- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'
  displayName: 'Publish SonarCloud analysis results'

- task: CopyFiles@2
  inputs:
    contents: 'build/**'
    targetFolder: '$(Build.ArtifactStagingDirectory)'
  displayName: 'Copy build output to artifact staging directory'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'drop'
  displayName: 'Publish build artifacts'



# Subir archivos a un bucket
- task: AWSCLI@1
  displayName: 'Sincronizar con S3'
  inputs:
    awsCredentials: 'DS2_SC_S3'
    regionName: 'us-east-1'
    awsCommand: 's3'
    awsSubCommand: 'sync'
    awsArguments: '. dist/ s3://$(bucket) --delete'

- template: notificaciones.yml@notificaciones